### PR TITLE
Allow non-root nodes to be used in partition & treemap

### LINKED ISSUE #91: Hierarchy layouts should allow non-root nodes as input?
When a descendant node (i.e depth != 0) is 'partitioned', it's children will be be positioned  inaccurately. 

screenshot from 2017-06-04 02-16-31
Here the 'world' node is 'partitioned' 
```js
partition()(world)
```

screenshot from 2017-06-04 02-16-55
Here the 'africa' node is partitioned, because the 'africa' node depth > 0, the layout gets broken
```js
partition()(africa)
```

### PR DESCRIPTION
**Pull request by jacobp100**
Fixes #91

### CODE REVIEW

**Comment by Misiu** [comment]
@jacobp100 what about other layouts? I think it's a good change, but it should work with other layouts too.
For example in tree. This would allow us to create this kind of layout:
snap 2017-10-10 at 15 34 00

**Comment by jacobp100** [comment]
Does d3 support anything close to that?

**Comment by Misiu** [comment]
Recently I had to build hierarchical layout for data without root (comes from external WS), I had to manually add root.
Having ability to specify non-root as source would make my life easier.
I'm waiting for ability to create layout extends, then having layout that I shown in my previous comment would be easy.

**Comment by jacobp100** [comment]
`d3`'s hierarchy structure doesn't support not having a single root

**Pull request closed without merging**
