### PR TITLE
Relax intersection test.

### LINKED ISSUE #109: d3.packSiblings overlaps, hangs.
Reference: https://beta.observablehq.com/@jediwarpraptor/market-capitalization-by-segment

```js
data = [
  {name: "a", value: 19492797890},
  {name: "b", value: 4196176},
  {name: "c", value: 14565064},
  {name: "d", value: 1243655681},
  {name: "e", value: 9756222871},
  {name: "f", value: 85483881441},
  {name: "g", value: 206472827707}
]
```

untitled 3

Dividing the data by ten should produce the same result, but apparently avoids the overlap:

```js
data = [
  {name: "a", value: 1949279789.0},
  {name: "b", value: 419617.6},
  {name: "c", value: 1456506.4},
  {name: "d", value: 124365568.1},
  {name: "e", value: 975622287.1},
  {name: "f", value: 8548388144.1},
  {name: "g", value: 20647282770.7}
]
```

untitled 4

Dividing the data by two results in an infinite loop!

```js
data = [
  {name: "a", value: 9746398945},
  {name: "b", value: 2098088},
  {name: "c", value: 7282532},
  {name: "d", value: 621827840.5},
  {name: "e", value: 4878111435.5},
  {name: "f", value: 42741940720.5},
  {name: "g", value: 103236413853.5}
]
```

Here’s a slightly reduced overlap case:

```js
data = [
  {name: "a", value: 4873199472.5},
  {name: "b", value: 1049044},
  {name: "d", value: 310913920.25},
  {name: "e", value: 2439055717.75},
  {name: "f", value: 21370970360.25}
]
```
untitled 5

### PR DESCRIPTION
**Pull request by mbostock**
Fixes #109. Applies a similar strategy to enclosesWeak. I also tweaked the arithmetic a tiny bit to maybe offer a tiny bit more precision. Look good, @robinhouston?

### CODE REVIEW

**Comment by robinhouston** [comment]
Okay, let me try and break it! :-)

**Comment by robinhouston** [comment]
No, I’m afraid it still breaks rather easily. I’ve pushed some test code in PR #112.

Here’s a sample failure:

```js
const a = { r: 0.8733723828537281, x: 104.30717184715218, y: 0 },
      b = { r: 104.30717184715218, x: -0.8733723828537281, y: 0 },
      c = { r: 15053206.77362454 };
place(a, b, c);
console.log(intersects(a, c)); // true
console.log(intersects(b, c)); // true
```

**Comment by robinhouston** [comment]
Suppose we were to make the intersection test **very** relaxed indeed:

```js
function intersects(a, b) {
  var dr = a.r + b.r - 0.1, dx = b.x - a.x, dy = b.y - a.y;
  return dr > 0 && dr * dr * 0.9 > dx * dx + dy * dy;
}
```

it still finds plenty of errors, e.g.
```js
a = {x: 271644298.81561947, y: 0, r: 1.0899431836479527},
b = {x: -1.0899431836479527, y: 0, r: 271644298.81561947},
c = {r: 0.7603609799366486}
```

Which suggests to me we need to think of something cleverer than relaxing the intersection test.

**Comment by robinhouston** [comment]
Here is a simple example where `place(a, b, c)` results in `c` overlapping a **lot** with both a and b:

```js
a = {x: 0.01, y: 0, r: 0.03},
b = {x: -0.03, y: 0, r: 0.01},
c = {r: 9e6};
```

**Comment by robinhouston** [comment]
Here’s a thing.

I tried a different implementation of the place function:

```js
function place(a, b, c) {
  var dx = b.x - a.x,
      dy = b.y - a.y,
      dc = dx * dx + dy * dy;
   if (dc) {
     var scale = Math.sqrt(dc);
     var ar = a.r / scale, br = b.r / scale, cr = c.r / scale;
     var x = (1 - (br - ar) * (ar + br + 2*cr)) / 2;
     var y = Math.sqrt(Math.max(0, (ar + cr) * (ar + cr) - x * x));
     c.x = a.x + x * dx + y * dy;
     c.y = a.y + x * dy - y * dx;
   } else {
    c.x = a.x + a.r + c.r;
    c.y = a.y;
   }
}
```

This implementation works okay in the cases where yours fails, i.e. where c is much larger than a and b. But it seems to fail in a different class of cases, where a is large but b and c are small.

So perhaps we can use a hybrid approach, where we switch algorithms depending on the inputs.

**Comment by mbostock** [comment]
Related https://github.com/d3/d3/commit/7c289774205b2e9da0def2253009f2756607874c https://github.com/d3/d3/commit/9b3e7800067511188f60f626ff8ce165519dcbf0.

**Comment by robinhouston** [comment]
Here is a version of the `place` function that seems to be holding up to my random testing so far:

```js
function place(a, b, c) {
  var dx = b.x - a.x,
      dy = b.y - a.y,
      dc = dx * dx + dy * dy;
  if (dc) {
    var scale = Math.sqrt(dc);
    var ar = a.r / scale, br = b.r / scale, cr = c.r / scale;
    var x, y;
    if (a.r > b.r) {
      x = (1 - (ar - br) * (ar + br + 2*cr)) / 2;
      y = Math.sqrt(Math.max(0, (br + cr) * (br + cr) - x * x));
      c.x = b.x - x * dx - y * dy;
      c.y = b.y - x * dy + y * dx;
    } else {
      x = (1 - (br - ar) * (ar + br + 2*cr)) / 2;
      y = Math.sqrt(Math.max(0, (ar + cr) * (ar + cr) - x * x));
      c.x = a.x + x * dx + y * dy;
      c.y = a.y + x * dy - y * dx;
    }
  } else {
    c.x = a.x + a.r + c.r;
    c.y = a.y;
  }
}
```

**Pull request merged**
